apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello from Node' > /mnt/data/hello.txt; sleep 3600"]
      volumeMounts:
        - mountPath: /mnt/data
          name: host-storage
  volumes:
    - name: host-storage
      hostPath:
        path: /data
        type: DirectoryOrCreate
