apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  namespace: admin-app
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: my-nginx
      image: nginx:alpine
      ports:
        - containerPort: 80