apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-svc
spec:
  type: NodePort
  selector:
    app: my-nginx-service-app
  ports:
  - port: 8082         # Service Port
    targetPort: 80
    nodePort: 30008   #Exposed NodePort [Between 30000-32767]
